### PR TITLE
Rerun also canceled and timed out jobs

### LINKED ISSUE #4: Rerun also cancelled and timed out jobs
### Description

It'd be good to also rerun all canceled and timed-out jobs when the command is executed. In order to merge a particular PR in the upstream, we need to have all required actions successful. However, sometimes, those jobs are canceled or timed out.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by mabartos**
Closes #4

@ahus1 @jonkoops @stianst Could you please check it?

### CODE REVIEW

**Comment by ahus1** [comment]
@mabartos - do you have an example PR at hand which would allow me to look at the data GitHub provide in its API?

**Comment by mabartos** [comment]
@ahus1 I haven't tried those changes for a real PR yet. And I don't know, what exactly do you mean with PR characterized as "which would allow me to look at the data GitHub provide in its API".

For instance, here is some PR with a canceled job.
https://github.com/keycloak/keycloak/pull/14310

**Comment by mabartos** [comment]
It'd be good if anybody from maintainers created some example PR(or me), cancel some jobs, and then execute the command. WDYT?

**Comment by ahus1** [comment]
Yes, this sounds good, and I believe it can be done in a separate test repository in a personal repository. 

I'm currently working on a different issue on the Keycloak project, might look at this one during the week. If anyone wants to tackle this before that, please do.

**Comment by mabartos** [comment]
@ahus1 Hmm, the approach with the personal repository might work. Thanks!

**Review by jonkoops — APPROVED** [review]

**Comment by jonkoops** [comment]
Changes look good, but I haven't tested them.

**Comment by mabartos** [comment]
@ahus1 @jonkoops It seems it's working as expected. I tried it in my fork in the main branch[1] and the canceled jobs are executed again. 
Btw. I guess the additional `(push)` jobs are related only to the fact, that I'm executing it in my own fork, where I have different privileges. The `pull_request` jobs are properly rerun. 

[1] https://github.com/mabartos/keycloak/pull/89

**Comment by ahus1** [comment]
Thanks for testing this, I agree this looks good!

**Pull request merged**
